### ISSUE TITLE
Possible issues with delegated rendering

### ISSUE THREAD

**Issue by yuchi** [metal/metal-react#2]
I’m sorry I have no time to actually test this, but I wanted to leave at least a note.

There are complex React components that expect functions as children. Those functions will be later called and of course they expect React elements to come out of those.

This means that your synchronous `incremental-dom → React element` transformation would happen just for the “first level” and not for the results of those functions.

``` js
ReactDOM.render(
  <Something>{ param => <span>{ param }</span> }</Something>,
  document.getElementById('something');
);
```

**Comment by mairatma** [comment]
Thanks for bringing this up, I really didn't know about this use case but now I see that components like [react-motion](https://github.com/chenglou/react-motion) use it.

We actually currently don't even allow passing functions as children, so right now we'd probably simply ignore it completely without passing it down. But I see that even if we already accepted functions we'd have the problem you've mentioned.

I think it's possible to fix this inside metal-react though. When converting children we can wrap these functions into another that can transform the results into react elements too.

This requires enabling functions to be passed as children first, so I'll try to take care of both of these :)

**Comment by yuchi** [comment]
Closing as this has moved to other issues.
