### ISSUE TITLE
Support for React 16.0.0

### ISSUE THREAD

**Issue by ssmith353** [metal/metal-react#4]
I'm trying to use a react component that requires 16.0.0, but metal-react uses 15.6.2, which causes 

`Uncaught Error: Unable to find node on an unmounted component.`

When trying to use two different versions of react together.

**Comment by jbalsas** [comment]
Hey @ssmith353, `metal-react@3.0.0` has been published with peerDependency support for `react>=15.0.0`. Let us know if you hit any other issues!

https://www.npmjs.com/package/metal-react
